### ISSUE TITLE
Which XML to add in the COMBINE archive?

### ISSUE THREAD

**Issue by freiburgermsu** [sys-bio/temp-biomodels#133]
Is there a systematic approach to selecting which XML file, where multiple are present, should be combined with the RDF metadata to produce the COMBINE archive? or is this manually determined for each BioModel?

**Comment by freiburgermsu** [comment]
Is this the code?
https://github.com/biosimulations/biomodels-qc/blob/639d644c0296427aea1dd56634144b735b471690/biomodels_qc/utils.py#L78-L108

**Comment by jonrkarr** [comment]
Yes

**Comment by jonrkarr** [comment]
I also have code already to apply this to this repo.

**Comment by freiburgermsu** [comment]
Is this code in the repository for me to use, or should I move to another task?

**Comment by jonrkarr** [comment]
I intended to use that code; unless a couple days ago, that code was in this repository.

**Comment by freiburgermsu** [comment]
I can move to generating SED-ML files for models that do not have one (task #3), since all of the BioModels appear to have RDF files which suggests that metadata does not need to be scraped (task #4) .

**Comment by jonrkarr** [comment]
Most of the remaining tasks, or at least their first steps, are easier for me to do. I already have code; I need to organize it into this repository.

- There's code for generating SED-ML
- The RDF in this repository encodes different metadata than what's on the BioModels website. I already have code for scraping the website and encoding that information into RDF.

**Comment by freiburgermsu** [comment]
Let me know if I can assist with anything else :)

Thank you,
    Andrew

**Comment by jonrkarr** [comment]
Hopefully I can put the code I have together this weekend. Then help would be great. I'd hate to have you repeat work I've already done, but haven't yet merged into this repo.

**Comment by luciansmith** [comment]
There's already a sedml file for the ones that were missing one.  Do we want a method for biosimulators-utils that does it? We could copy the code over.
