### ISSUE TITLE
Move biomodels_qc package to permanent location

### ISSUE THREAD

**Issue by jonrkarr** [sys-bio/temp-biomodels#38]
After the initial BioModels cleanup is done:

- [ ] Move package to permanent location: https://github.com/reproducible-biomedical-modeling/biomodels_qc
- [ ] Setup saving coverage data to CodeCov
- [ ] Setup secrets to push Docker image to GHCR
- [ ] Setup secret to push package to PyPI

**Comment by luciansmith** [comment]
biomodels_qc has been uploaded to pypi:

https://pypi.org/project/biomodels-qc/

It probably still needs a more permanent home, however.

**Comment by jonrkarr** [comment]
I already moved this to https://github.com/biosimulations/biomodels-qc.
