### ISSUE TITLE
Encode scatter plots (markers, no line) in SED-ML

### ISSUE THREAD

**Issue by jonrkarr** [sys-bio/temp-biomodels#82]
From experience, the difference in style (between scatter and line) can cause some plots to appear to be erroneously generated.

Use COPASI files to determine which plots require scatter style, and delete them.

**Comment by luciansmith** [comment]
With https://github.com/sys-bio/temp-biomodels/commit/fb53dd1dc0345a96e2766242919523edadb77ea5 this should now all work.
